// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":false,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Olivia_MapDisplayNameCore","status":true,"description":"<MapDisplayNameCore> for RPG Maker MV version 1.6.1.","parameters":{"":"","ATTENTION!!!":"READ THE HELP FILE","Text Distance":"80","Window Height":"36","Y Position":"","Starting Y":"18","Middle Y":"48","Ending Y":"78","Fade":"","Fade In Time":"60","Middle Time":"60","Fade Out Time":"60","Dim Color":"","Dim Color 1":"rgba(0, 0, 0, 0.6)","Dim Color 2":"rgba(0, 0, 0, 0)"}}
];
